2017-12-28 15:30:46 pid:1 Error: Cannot access empty property in D:\web\WWW\hanzi\public\lib\app\test\workerman.php:46
Stack trace:
#0 [internal function]: lib\app\test\{closure}(Object(Workerman\Connection\TcpConnection))
#1 D:\web\WWW\hanzi\public\vendor\workerman\workerman\Connection\TcpConnection.php(868): call_user_func(Object(Closure), Object(Workerman\Connection\TcpConnection))
#2 D:\web\WWW\hanzi\public\vendor\workerman\workerman\Connection\TcpConnection.php(782): Workerman\Connection\TcpConnection->destroy()
#3 D:\web\WWW\hanzi\public\vendor\workerman\workerman\Protocols\Websocket.php(98): Workerman\Connection\TcpConnection->close()
#4 D:\web\WWW\hanzi\public\vendor\workerman\workerman\Connection\TcpConnection.php(621): Workerman\Protocols\Websocket::input('\x88\x82\xF2\xA3g\x86\xF1J', Object(Workerman\Connection\TcpConnection))
#5 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #32)
#6 D:\web\WWW\hanzi\public\vendor\workerman\workerman\Events\Select.php(286): call_user_func_array(Array, Array)
#7 D:\web\WWW\hanzi\public\vendor\workerman\workerman\Worker.php(2096): Workerman\Events\Select->loop()
#8 D:\web\WWW\hanzi\public\vendor\workerman\workerman\Worker.php(1160): Workerman\Worker->run()
#9 D:\web\WWW\hanzi\public\vendor\workerman\workerman\Worker.php(1102): Workerman\Worker::forkWorkersForWindows()
#10 D:\web\WWW\hanzi\public\vendor\workerman\workerman\Worker.php(459): Workerman\Worker::forkWorkers()
#11 D:\web\WWW\hanzi\public\lib\app\test\workerman.php(51): Workerman\Worker::runAll()
#12 D:\web\WWW\hanzi\public\lib\app\test\workerman.php(9): lib\app\test\runWorker()
#13 D:\web\WWW\hanzi\public\lib\workerman.php(8): lib\app\test\workerman->index()
#14 {main}
2017-12-28 15:30:46 pid:1 Worker process terminated
2018-01-09 16:07:48 pid:1 Worker process terminated with ERROR: E_RECOVERABLE_ERROR "Object of class Workerman\Connection\TcpConnection could not be converted to string in D:\web\WWW\blog\lib\app\test\workerman.php on line 34"
2018-01-09 16:12:26 pid:1 Worker process terminated with ERROR: E_RECOVERABLE_ERROR "Object of class Workerman\Connection\TcpConnection could not be converted to string in D:\web\WWW\blog\lib\app\test\workerman.php on line 53"
2018-01-11 16:00:47 pid:1 Error: Class 'lib\app\test\server\Db' not found in D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php:28
Stack trace:
#0 [internal function]: lib\app\test\server\{closure}(Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#1 D:\web\WWW\blog\vendor\workerman\workerman\Connection\TcpConnection.php(657): call_user_func(Object(Closure), Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#2 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #37)
#3 D:\web\WWW\blog\vendor\workerman\workerman\Events\Select.php(286): call_user_func_array(Array, Array)
#4 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(2096): Workerman\Events\Select->loop()
#5 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1160): Workerman\Worker->run()
#6 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1102): Workerman\Worker::forkWorkersForWindows()
#7 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(459): Workerman\Worker::forkWorkers()
#8 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(34): Workerman\Worker::runAll()
#9 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(8): lib\app\test\server\runWorkerTest3()
#10 D:\web\WWW\blog\lib\app\test\workerman.php(20): lib\app\test\server\runWorkerTest3->runWorker()
#11 D:\web\WWW\blog\lib\command\workerman\runWorkerTest3.php(8): lib\app\test\workerman->runWorkerTest3()
#12 {main}
2018-01-11 16:00:47 pid:1 Worker process terminated
2018-01-11 16:01:35 pid:1 InvalidArgumentException: Undefined db type in D:\web\WWW\blog\vendor\topthink\think-orm\src\db\Connection.php:178
Stack trace:
#0 D:\web\WWW\blog\vendor\topthink\think-orm\src\db\Query.php(73): think\db\Connection::instance()
#1 D:\web\WWW\blog\vendor\topthink\think-orm\src\Db.php(150): think\db\Query->__construct()
#2 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(29): think\Db::__callStatic('name', Array)
#3 [internal function]: lib\app\test\server\{closure}(Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#4 D:\web\WWW\blog\vendor\workerman\workerman\Connection\TcpConnection.php(657): call_user_func(Object(Closure), Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#5 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #37)
#6 D:\web\WWW\blog\vendor\workerman\workerman\Events\Select.php(286): call_user_func_array(Array, Array)
#7 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(2096): Workerman\Events\Select->loop()
#8 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1160): Workerman\Worker->run()
#9 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1102): Workerman\Worker::forkWorkersForWindows()
#10 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(459): Workerman\Worker::forkWorkers()
#11 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(35): Workerman\Worker::runAll()
#12 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(9): lib\app\test\server\runWorkerTest3()
#13 D:\web\WWW\blog\lib\app\test\workerman.php(20): lib\app\test\server\runWorkerTest3->runWorker()
#14 D:\web\WWW\blog\lib\command\workerman\runWorkerTest3.php(8): lib\app\test\workerman->runWorkerTest3()
#15 {main}
2018-01-11 16:01:35 pid:1 Worker process terminated
2018-01-11 16:33:25 pid:1 Error: Call to undefined method lib\obj\mysql::find() in D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php:52
Stack trace:
#0 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(44): lib\app\test\server\addNewUser(NULL, Object(Workerman\Connection\TcpConnection), '123')
#1 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(27): lib\app\test\server\dealMessage(NULL, Object(Workerman\Connection\TcpConnection), Array)
#2 [internal function]: lib\app\test\server\{closure}(Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#3 D:\web\WWW\blog\vendor\workerman\workerman\Connection\TcpConnection.php(657): call_user_func(Object(Closure), Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#4 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #37)
#5 D:\web\WWW\blog\vendor\workerman\workerman\Events\Select.php(286): call_user_func_array(Array, Array)
#6 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(2096): Workerman\Events\Select->loop()
#7 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1160): Workerman\Worker->run()
#8 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1102): Workerman\Worker::forkWorkersForWindows()
#9 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(459): Workerman\Worker::forkWorkers()
#10 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(34): Workerman\Worker::runAll()
#11 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(8): lib\app\test\server\runWorkerTest3()
#12 D:\web\WWW\blog\lib\app\test\workerman.php(20): lib\app\test\server\runWorkerTest3->runWorker()
#13 D:\web\WWW\blog\lib\command\workerman\runWorkerTest3.php(8): lib\app\test\workerman->runWorkerTest3()
#14 {main}
2018-01-11 16:33:25 pid:1 Worker process terminated
2018-01-11 16:41:22 pid:1 Error: Call to undefined method lib\obj\mysql::find() in D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php:52
Stack trace:
#0 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(44): lib\app\test\server\addNewUser(NULL, Object(Workerman\Connection\TcpConnection), '123')
#1 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(27): lib\app\test\server\dealMessage(NULL, Object(Workerman\Connection\TcpConnection), Array)
#2 [internal function]: lib\app\test\server\{closure}(Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#3 D:\web\WWW\blog\vendor\workerman\workerman\Connection\TcpConnection.php(657): call_user_func(Object(Closure), Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#4 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #37)
#5 D:\web\WWW\blog\vendor\workerman\workerman\Events\Select.php(286): call_user_func_array(Array, Array)
#6 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(2096): Workerman\Events\Select->loop()
#7 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1160): Workerman\Worker->run()
#8 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1102): Workerman\Worker::forkWorkersForWindows()
#9 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(459): Workerman\Worker::forkWorkers()
#10 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(34): Workerman\Worker::runAll()
#11 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(8): lib\app\test\server\runWorkerTest3()
#12 D:\web\WWW\blog\lib\app\test\workerman.php(20): lib\app\test\server\runWorkerTest3->runWorker()
#13 D:\web\WWW\blog\lib\command\workerman\runWorkerTest3.php(8): lib\app\test\workerman->runWorkerTest3()
#14 {main}
2018-01-11 16:41:22 pid:1 Worker process terminated
2018-01-11 16:41:44 pid:1 Error: Call to undefined method lib\obj\mysql::find() in D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php:52
Stack trace:
#0 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(44): lib\app\test\server\addNewUser(NULL, Object(Workerman\Connection\TcpConnection), '123')
#1 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(27): lib\app\test\server\dealMessage(NULL, Object(Workerman\Connection\TcpConnection), Array)
#2 [internal function]: lib\app\test\server\{closure}(Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#3 D:\web\WWW\blog\vendor\workerman\workerman\Connection\TcpConnection.php(657): call_user_func(Object(Closure), Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#4 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #43)
#5 D:\web\WWW\blog\vendor\workerman\workerman\Events\Select.php(286): call_user_func_array(Array, Array)
#6 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(2096): Workerman\Events\Select->loop()
#7 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1160): Workerman\Worker->run()
#8 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1102): Workerman\Worker::forkWorkersForWindows()
#9 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(459): Workerman\Worker::forkWorkers()
#10 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(34): Workerman\Worker::runAll()
#11 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(8): lib\app\test\server\runWorkerTest3()
#12 D:\web\WWW\blog\lib\app\test\workerman.php(22): lib\app\test\server\runWorkerTest3->runWorker()
#13 D:\web\WWW\blog\lib\command\workerman\runWorkerTest3.php(8): lib\app\test\workerman->runWorkerTest3()
#14 {main}
2018-01-11 16:41:44 pid:1 Worker process terminated
2018-01-11 16:43:04 pid:1 think\db\exception\PDOException: SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value in D:\web\WWW\blog\vendor\topthink\think-orm\src\db\Connection.php:742
Stack trace:
#0 D:\web\WWW\blog\vendor\topthink\think-orm\src\db\Connection.php(936): think\db\Connection->execute('INSERT INTO `us...', Array)
#1 D:\web\WWW\blog\vendor\topthink\think-orm\src\db\Query.php(2078): think\db\Connection->insert(Object(think\db\Query), false, false, NULL)
#2 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(63): think\db\Query->insert(Array)
#3 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(45): lib\app\test\server\addNewUser(NULL, Object(Workerman\Connection\TcpConnection), '123')
#4 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(28): lib\app\test\server\dealMessage(NULL, Object(Workerman\Connection\TcpConnection), Array)
#5 [internal function]: lib\app\test\server\{closure}(Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#6 D:\web\WWW\blog\vendor\workerman\workerman\Connection\TcpConnection.php(657): call_user_func(Object(Closure), Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#7 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #43)
#8 D:\web\WWW\blog\vendor\workerman\workerman\Events\Select.php(286): call_user_func_array(Array, Array)
#9 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(2096): Workerman\Events\Select->loop()
#10 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1160): Workerman\Worker->run()
#11 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1102): Workerman\Worker::forkWorkersForWindows()
#12 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(459): Workerman\Worker::forkWorkers()
#13 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(35): Workerman\Worker::runAll()
#14 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(9): lib\app\test\server\runWorkerTest3()
#15 D:\web\WWW\blog\lib\app\test\workerman.php(21): lib\app\test\server\runWorkerTest3->runWorker()
#16 D:\web\WWW\blog\lib\command\workerman\runWorkerTest3.php(8): lib\app\test\workerman->runWorkerTest3()
#17 {main}
2018-01-11 16:43:04 pid:1 Worker process terminated
2018-01-11 17:02:35 pid:1 think\db\exception\PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'username' cannot be null in D:\web\WWW\blog\vendor\topthink\think-orm\src\db\Connection.php:742
Stack trace:
#0 D:\web\WWW\blog\vendor\topthink\think-orm\src\db\Connection.php(936): think\db\Connection->execute('INSERT INTO `us...', Array)
#1 D:\web\WWW\blog\vendor\topthink\think-orm\src\db\Query.php(2078): think\db\Connection->insert(Object(think\db\Query), false, false, NULL)
#2 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(62): think\db\Query->insert(Array)
#3 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(44): lib\app\test\server\addNewUser(NULL, Object(Workerman\Connection\TcpConnection), NULL)
#4 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(28): lib\app\test\server\dealMessage(NULL, Object(Workerman\Connection\TcpConnection), Array)
#5 [internal function]: lib\app\test\server\{closure}(Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#6 D:\web\WWW\blog\vendor\workerman\workerman\Connection\TcpConnection.php(657): call_user_func(Object(Closure), Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#7 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #73)
#8 D:\web\WWW\blog\vendor\workerman\workerman\Events\Select.php(286): call_user_func_array(Array, Array)
#9 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(2096): Workerman\Events\Select->loop()
#10 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1160): Workerman\Worker->run()
#11 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1102): Workerman\Worker::forkWorkersForWindows()
#12 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(459): Workerman\Worker::forkWorkers()
#13 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(34): Workerman\Worker::runAll()
#14 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(9): lib\app\test\server\runWorkerTest3()
#15 D:\web\WWW\blog\lib\app\test\workerman.php(21): lib\app\test\server\runWorkerTest3->runWorker()
#16 D:\web\WWW\blog\lib\command\workerman\runWorkerTest3.php(8): lib\app\test\workerman->runWorkerTest3()
#17 {main}
2018-01-11 17:02:35 pid:1 Worker process terminated
2018-01-11 17:39:40 pid:1 think\db\exception\PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '7' for key 'username' in D:\web\WWW\blog\vendor\topthink\think-orm\src\db\Connection.php:742
Stack trace:
#0 D:\web\WWW\blog\vendor\topthink\think-orm\src\db\Connection.php(1103): think\db\Connection->execute('UPDATE `user`  ...', Array)
#1 D:\web\WWW\blog\vendor\topthink\think-orm\src\db\Query.php(2138): think\db\Connection->update(Object(think\db\Query))
#2 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(79): think\db\Query->update(Array)
#3 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(45): lib\app\test\server\addNewUser(NULL, Object(Workerman\Connection\TcpConnection), '7')
#4 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(28): lib\app\test\server\dealMessage(NULL, Object(Workerman\Connection\TcpConnection), Array)
#5 [internal function]: lib\app\test\server\{closure}(Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#6 D:\web\WWW\blog\vendor\workerman\workerman\Connection\TcpConnection.php(657): call_user_func(Object(Closure), Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#7 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #43)
#8 D:\web\WWW\blog\vendor\workerman\workerman\Events\Select.php(286): call_user_func_array(Array, Array)
#9 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(2096): Workerman\Events\Select->loop()
#10 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1160): Workerman\Worker->run()
#11 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1102): Workerman\Worker::forkWorkersForWindows()
#12 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(459): Workerman\Worker::forkWorkers()
#13 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(35): Workerman\Worker::runAll()
#14 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(9): lib\app\test\server\runWorkerTest3()
#15 D:\web\WWW\blog\lib\app\test\workerman.php(21): lib\app\test\server\runWorkerTest3->runWorker()
#16 D:\web\WWW\blog\lib\command\workerman\runWorkerTest3.php(8): lib\app\test\workerman->runWorkerTest3()
#17 {main}
2018-01-11 17:39:40 pid:1 Worker process terminated
2018-01-11 17:43:48 pid:1 think\db\exception\PDOException: SQLSTATE[HY000]: General error: 1364 Field 'close_time' doesn't have a default value in D:\web\WWW\blog\vendor\topthink\think-orm\src\db\Connection.php:742
Stack trace:
#0 D:\web\WWW\blog\vendor\topthink\think-orm\src\db\Connection.php(936): think\db\Connection->execute('INSERT INTO `us...', Array)
#1 D:\web\WWW\blog\vendor\topthink\think-orm\src\db\Query.php(2078): think\db\Connection->insert(Object(think\db\Query), false, false, NULL)
#2 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(73): think\db\Query->insert(Array)
#3 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(45): lib\app\test\server\addNewUser(NULL, Object(Workerman\Connection\TcpConnection), '8')
#4 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(28): lib\app\test\server\dealMessage(NULL, Object(Workerman\Connection\TcpConnection), Array)
#5 [internal function]: lib\app\test\server\{closure}(Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#6 D:\web\WWW\blog\vendor\workerman\workerman\Connection\TcpConnection.php(657): call_user_func(Object(Closure), Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#7 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #54)
#8 D:\web\WWW\blog\vendor\workerman\workerman\Events\Select.php(286): call_user_func_array(Array, Array)
#9 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(2096): Workerman\Events\Select->loop()
#10 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1160): Workerman\Worker->run()
#11 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1102): Workerman\Worker::forkWorkersForWindows()
#12 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(459): Workerman\Worker::forkWorkers()
#13 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(35): Workerman\Worker::runAll()
#14 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(9): lib\app\test\server\runWorkerTest3()
#15 D:\web\WWW\blog\lib\app\test\workerman.php(21): lib\app\test\server\runWorkerTest3->runWorker()
#16 D:\web\WWW\blog\lib\command\workerman\runWorkerTest3.php(8): lib\app\test\workerman->runWorkerTest3()
#17 {main}
2018-01-11 17:43:48 pid:1 Worker process terminated
2018-01-11 18:01:57 pid:1 think\db\exception\PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '骨傲天-0' for key 'username' in D:\web\WWW\blog\vendor\topthink\think-orm\src\db\Connection.php:742
Stack trace:
#0 D:\web\WWW\blog\vendor\topthink\think-orm\src\db\Connection.php(1103): think\db\Connection->execute('UPDATE `user`  ...', Array)
#1 D:\web\WWW\blog\vendor\topthink\think-orm\src\db\Query.php(2138): think\db\Connection->update(Object(think\db\Query))
#2 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(114): think\db\Query->update(Array)
#3 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(32): lib\app\test\server\dealClose(NULL, Object(Workerman\Connection\TcpConnection))
#4 [internal function]: lib\app\test\server\{closure}(Object(Workerman\Connection\TcpConnection))
#5 D:\web\WWW\blog\vendor\workerman\workerman\Connection\TcpConnection.php(868): call_user_func(Object(Closure), Object(Workerman\Connection\TcpConnection))
#6 D:\web\WWW\blog\vendor\workerman\workerman\Connection\TcpConnection.php(782): Workerman\Connection\TcpConnection->destroy()
#7 D:\web\WWW\blog\vendor\workerman\workerman\Protocols\Websocket.php(98): Workerman\Connection\TcpConnection->close()
#8 D:\web\WWW\blog\vendor\workerman\workerman\Connection\TcpConnection.php(621): Workerman\Protocols\Websocket::input('\x88\x82\x9F\x9AC\xEB\x9Cs', Object(Workerman\Connection\TcpConnection))
#9 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #68)
#10 D:\web\WWW\blog\vendor\workerman\workerman\Events\Select.php(286): call_user_func_array(Array, Array)
#11 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(2096): Workerman\Events\Select->loop()
#12 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1160): Workerman\Worker->run()
#13 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1102): Workerman\Worker::forkWorkersForWindows()
#14 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(459): Workerman\Worker::forkWorkers()
#15 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(35): Workerman\Worker::runAll()
#16 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(9): lib\app\test\server\runWorkerTest3()
#17 D:\web\WWW\blog\lib\app\test\workerman.php(21): lib\app\test\server\runWorkerTest3->runWorker()
#18 D:\web\WWW\blog\lib\command\workerman\runWorkerTest3.php(8): lib\app\test\workerman->runWorkerTest3()
#19 {main}
2018-01-11 18:01:57 pid:1 Worker process terminated
2018-01-11 18:19:22 pid:1 think\Exception: method not exist:think\db\Query->wherr in D:\web\WWW\blog\vendor\topthink\think-orm\src\db\Query.php:131
Stack trace:
#0 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(61): think\db\Query->__call('wherr', Array)
#1 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(45): lib\app\test\server\addNewUser(NULL, Object(Workerman\Connection\TcpConnection), '6')
#2 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(28): lib\app\test\server\dealMessage(NULL, Object(Workerman\Connection\TcpConnection), Array)
#3 [internal function]: lib\app\test\server\{closure}(Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#4 D:\web\WWW\blog\vendor\workerman\workerman\Connection\TcpConnection.php(657): call_user_func(Object(Closure), Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#5 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #43)
#6 D:\web\WWW\blog\vendor\workerman\workerman\Events\Select.php(286): call_user_func_array(Array, Array)
#7 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(2096): Workerman\Events\Select->loop()
#8 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1160): Workerman\Worker->run()
#9 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1102): Workerman\Worker::forkWorkersForWindows()
#10 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(459): Workerman\Worker::forkWorkers()
#11 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(35): Workerman\Worker::runAll()
#12 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(9): lib\app\test\server\runWorkerTest3()
#13 D:\web\WWW\blog\lib\app\test\workerman.php(21): lib\app\test\server\runWorkerTest3->runWorker()
#14 D:\web\WWW\blog\lib\command\workerman\runWorkerTest3.php(8): lib\app\test\workerman->runWorkerTest3()
#15 {main}
2018-01-11 18:19:22 pid:1 Worker process terminated
2018-01-11 18:21:33 pid:1 Exception: miss update condition in D:\web\WWW\blog\vendor\topthink\think-orm\src\db\Connection.php:1076
Stack trace:
#0 D:\web\WWW\blog\vendor\topthink\think-orm\src\db\Query.php(2138): think\db\Connection->update(Object(think\db\Query))
#1 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(83): think\db\Query->update(Array)
#2 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(45): lib\app\test\server\addNewUser(NULL, Object(Workerman\Connection\TcpConnection), '\xE9\xBE\x99\xE5\x82\xB2\xE5\xA4\xA9')
#3 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(28): lib\app\test\server\dealMessage(NULL, Object(Workerman\Connection\TcpConnection), Array)
#4 [internal function]: lib\app\test\server\{closure}(Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#5 D:\web\WWW\blog\vendor\workerman\workerman\Connection\TcpConnection.php(657): call_user_func(Object(Closure), Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#6 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #54)
#7 D:\web\WWW\blog\vendor\workerman\workerman\Events\Select.php(286): call_user_func_array(Array, Array)
#8 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(2096): Workerman\Events\Select->loop()
#9 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1160): Workerman\Worker->run()
#10 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1102): Workerman\Worker::forkWorkersForWindows()
#11 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(459): Workerman\Worker::forkWorkers()
#12 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(35): Workerman\Worker::runAll()
#13 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(9): lib\app\test\server\runWorkerTest3()
#14 D:\web\WWW\blog\lib\app\test\workerman.php(21): lib\app\test\server\runWorkerTest3->runWorker()
#15 D:\web\WWW\blog\lib\command\workerman\runWorkerTest3.php(8): lib\app\test\workerman->runWorkerTest3()
#16 {main}
2018-01-11 18:21:33 pid:1 Worker process terminated
2018-01-12 09:55:04 pid:1 Exception: error in D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php:33
Stack trace:
#0 [internal function]: lib\app\test\server\{closure}(Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#1 D:\web\WWW\blog\vendor\workerman\workerman\Connection\TcpConnection.php(657): call_user_func(Object(Closure), Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#2 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #43)
#3 D:\web\WWW\blog\vendor\workerman\workerman\Events\Select.php(286): call_user_func_array(Array, Array)
#4 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(2096): Workerman\Events\Select->loop()
#5 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1160): Workerman\Worker->run()
#6 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1102): Workerman\Worker::forkWorkersForWindows()
#7 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(459): Workerman\Worker::forkWorkers()
#8 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(40): Workerman\Worker::runAll()
#9 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(10): lib\app\test\server\runWorkerTest3()
#10 D:\web\WWW\blog\lib\app\test\workerman.php(21): lib\app\test\server\runWorkerTest3->runWorker()
#11 D:\web\WWW\blog\lib\command\workerman\runWorkerTest3.php(8): lib\app\test\workerman->runWorkerTest3()
#12 {main}
2018-01-12 09:55:04 pid:1 Worker process terminated
2018-01-12 09:58:11 pid:1 Exception: error in D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php:33
Stack trace:
#0 [internal function]: lib\app\test\server\{closure}(Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#1 D:\web\WWW\blog\vendor\workerman\workerman\Connection\TcpConnection.php(657): call_user_func(Object(Closure), Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#2 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #43)
#3 D:\web\WWW\blog\vendor\workerman\workerman\Events\Select.php(286): call_user_func_array(Array, Array)
#4 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(2096): Workerman\Events\Select->loop()
#5 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1160): Workerman\Worker->run()
#6 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1102): Workerman\Worker::forkWorkersForWindows()
#7 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(459): Workerman\Worker::forkWorkers()
#8 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(40): Workerman\Worker::runAll()
#9 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(10): lib\app\test\server\runWorkerTest3()
#10 D:\web\WWW\blog\lib\app\test\workerman.php(21): lib\app\test\server\runWorkerTest3->runWorker()
#11 D:\web\WWW\blog\lib\command\workerman\runWorkerTest3.php(8): lib\app\test\workerman->runWorkerTest3()
#12 {main}
2018-01-12 09:58:11 pid:1 Worker process terminated
2018-01-12 10:02:09 pid:1 Exception: error in D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php:33
Stack trace:
#0 [internal function]: lib\app\test\server\{closure}(Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#1 D:\web\WWW\blog\vendor\workerman\workerman\Connection\TcpConnection.php(657): call_user_func(Object(Closure), Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#2 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #43)
#3 D:\web\WWW\blog\vendor\workerman\workerman\Events\Select.php(286): call_user_func_array(Array, Array)
#4 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(2096): Workerman\Events\Select->loop()
#5 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1160): Workerman\Worker->run()
#6 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1102): Workerman\Worker::forkWorkersForWindows()
#7 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(459): Workerman\Worker::forkWorkers()
#8 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(40): Workerman\Worker::runAll()
#9 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(10): lib\app\test\server\runWorkerTest3()
#10 D:\web\WWW\blog\lib\app\test\workerman.php(26): lib\app\test\server\runWorkerTest3->runWorker()
#11 D:\web\WWW\blog\lib\command\workerman\runWorkerTest3.php(8): lib\app\test\workerman->runWorkerTest3()
#12 {main}
2018-01-12 10:02:09 pid:1 Worker process terminated
2018-01-23 15:45:02 pid:1 Error: Call to undefined function lib\app\test\server\dealMessageCatch() in D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php:30
Stack trace:
#0 [internal function]: lib\app\test\server\{closure}(Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#1 D:\web\WWW\blog\vendor\workerman\workerman\Connection\TcpConnection.php(657): call_user_func(Object(Closure), Object(Workerman\Connection\TcpConnection), '{"action":"init...')
#2 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #43)
#3 D:\web\WWW\blog\vendor\workerman\workerman\Events\Select.php(286): call_user_func_array(Array, Array)
#4 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(2096): Workerman\Events\Select->loop()
#5 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1160): Workerman\Worker->run()
#6 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(1102): Workerman\Worker::forkWorkersForWindows()
#7 D:\web\WWW\blog\vendor\workerman\workerman\Worker.php(459): Workerman\Worker::forkWorkers()
#8 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(47): Workerman\Worker::runAll()
#9 D:\web\WWW\blog\lib\app\test\server\runWorkerTest3.php(9): lib\app\test\server\runWorkerTest3()
#10 D:\web\WWW\blog\lib\app\test\workerman.php(25): lib\app\test\server\runWorkerTest3->runWorker()
#11 D:\web\WWW\blog\lib\command\workerman\runWorkerTest3.php(8): lib\app\test\workerman->runWorkerTest3()
#12 {main}
2018-01-23 15:45:02 pid:1 Worker process terminated
